基本項目:
  - 枠順:
      color_rules:
        - {labels: [1枠, 2枠, 3枠, 4枠], color: yellow}
  - 前走脚質:
      color_rules:
        - {labels: [逃げ, 先行], color: yellow}
  - 前走4角通過順位:
      color_rules:
        - {labels: [1番手, 2-5番手], color: yellow}
        - {labels: [10番手以下], color: gray}
  - 所属:
      color_rules:
        - {labels: [美浦], color: yellow}
  - 馬齢:
      color_rules:
        - {labels: [4歳], color: yellow}
前走:
  - 前走レース:
      color_rules:
        - {labels: [産経賞セントウルステークス, キーンランドカップ, テレビ西日本賞北九州記念, 安田記念, ＣＢＣ賞], color: yellow}
        - {labels: [アイビスサマーダッシュ], color: gray}
  - 前走距離:
      color_rules:
        - {labels: [距離短縮], color: yellow}
        - {labels: [距離延長], color: gray}
  - 前走クラス着順:
      color_rules:
        - {labels: [G1 1着, G1 2着, G1 3着], color: yellow}
        - {labels: [G2 3着, G2 4着, G2 5着, G2 6-9着, G2 10着以下, G3 6-9着, G3 10着以下, 非重賞 1着, 非重賞 2着, 非重賞 3着, 非重賞 4着, 非重賞 5着, 非重賞 6-9着, 非重賞 10着以下], color: gray}
調教:
  - 当週/1週前坂路ラスト2F24.0秒未満:
      color_rules:
        - {labels: [該当], color: yellow}
同年/前年レース実績:
  - 同年高松宮記念着順:
      color_rules:
        - {labels: [3着以内], color: yellow}
馬以外の属性:
  - 騎手:
      color_rules:
        - {metric: 3着内数, op: ">=", value: 2, color: yellow}
  - 生産者:
      color_rules:
        - {labels: [ノーザンファーム], color: yellow}
