基本項目:
  - 枠順:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 前走脚質:
      color_rules:
        - {labels: [逃げ, 先行], color: yellow}
  - 前走上がり3F順位:
      color_rules:
        - {labels: [1位], color: yellow}
  - 所属:
      color_rules:
        - {labels: [美浦], color: yellow}
  - 馬齢:
      color_rules:
        - {labels: [4歳], color: yellow}
  - 性別:
      color_rules:
        - {labels: [牡], color: yellow}
前走:
  - 前走レース:
      color_rules:
        - {labels: [産経賞セントウルステークス, キーンランドカップ, テレビ西日本賞北九州記念, 安田記念], color: yellow}
        - {labels: [アイビスサマーダッシュ], color: gray}
  - 前走距離:
      color_rules:
        - {labels: [距離短縮], color: yellow}
        - {labels: [距離延長], color: gray}
  - 前走G1着順:
      color_rules:
        - {labels: [1着, 2着, 3着, 4着, 5着, 6-9着, 10着以下], color: yellow}
  - 前走G2着順:
      color_rules:
        - {labels: [1着], color: yellow}
実績:
  - リピーター
調教:
  - 当週/1週前坂路ラスト2F24.0秒未満:
      color_rules:
        - {labels: [該当], color: yellow}
同年/前年レース実績:
  - 同年高松宮記念着順:
      color_rules:
        - {labels: [3着以内], color: yellow}
馬以外の属性:
  - 騎手:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 生産者:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 種牡馬:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
