基本項目:
  - 人気
  - 枠順
  - 脚質
  - 前走脚質
  - 4角通過順位
  - 前走4角通過順位
  - 上がり3F順位
  - 前走上がり3F順位
  - 所属
  - 馬齢
  - 性別
  - 馬体重
  - 輸送
前走:
  - 前走レース
  - 前走着順
  - 前走距離
  - 前走クラス
  - 前走G1着順
  - 前走G2着順
  - 前走G3着順
  - 前走非重賞着順
実績:
  - 勝利数
  - 重賞勝利数
  - 中山勝利数
  - 中山重賞好走実績
  - リピーター
  - 良馬場好走実績
  - 稍重以上好走実績
調教:
  - 当週/1週前坂路ラスト2F24.0秒未満
同年/前年レース実績:
  - 同年高松宮記念着順
馬以外の属性:
  - 騎手
  - 生産者
  - 種牡馬
