基本項目:
  - 枠順:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 前走脚質:
      color_rules:
        - {labels: [逃げ, 先行], color: yellow}
前走:
  - 前走レース:
      color_rules:
        - {labels: [皐月賞], color: yellow}
実績:
  - 勝利数:
      color_rules:
        - {labels: [3勝以上], color: yellow}
  - 重賞勝利数:
      color_rules:
        - {labels: [1勝, 2勝以上], color: yellow}
  - 東京勝利数:
      color_rules:
        - {labels: [1勝, 2勝以上], color: yellow}
世代戦:
  - デビュー競馬場:
      color_rules:
        - {labels: [東京], color: yellow}
  - キャリア:
      color_rules:
        - {labels: [4戦, 5戦], color: yellow}
馬以外の属性:
  - 騎手:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 生産者:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 種牡馬:
      color_rules:
        - {metric: 複勝率, op: ">=", value: 30, color: yellow}
  - 継続騎乗:
      color_rules:
        - {labels: [継続騎乗], color: yellow}
  - 父実績:
      color_rules:
        - {labels: [父東京優駿勝ち], color: yellow}
